# http://docs.ansible.com/playbooks_intro.html#tasks-list
- name: install nginx
  apt: name=nginx

- name: add site config
  template: src=dclaw.j2 dest=/etc/nginx/sites-available/dccode
  notify: restart nginx

- name: enable site
  file: name=/etc/nginx/sites-enabled/dccode src=/etc/nginx/sites-available/dccode state=link
  notify: restart nginx

- name: template ssl files
  template: src={{item}}.j2 dest=/etc/ssl/{{item}} owner=root mode=0600
  with_items:
    - dccouncil.us.crt
    - dccouncil.us.key
    - dccouncil.us.chain
  notify: restart nginx

- name: remove default site
  file: name=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
